version: '3'

services:
    app:
        container_name: hpay-report-nhnn
        image: hpay-web-report-nhnn:latest
        build:
            context: .
            target: runner
        ports:
            - 7001:3000
        environment:
            - NODE_ENV=production
            - NEXT_TELEMETRY_DISABLED=1
        user: nextjs
