version: '3'

services:
    app:
        build:
            context: .
            target: runner
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=production
            - NEXT_TELEMETRY_DISABLED=1
        user: nextjs
