version: '3'
services:
    #PHP Service
    app:
        container_name: app-laravel
        image: app-laravel:latest
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        restart: always
        ports:
            - 7002:80
        environment:
            SERVICE_NAME: app-laravel
            SERVICE_TAGS: dev
        volumes:
            - ./:/var/www/html
            - /var/www/html/vendor
        entrypoint: ["/usr/local/bin/start.sh"]
        networks:
            - app-network
#Docker Networks
networks:
    app-network:
        driver: bridge
