version: '3'
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app_laravel
        restart: unless-stopped
        tty: true
        ports:
            - 9099:80
        environment:
            SERVICE_NAME: app_laravel
            SERVICE_TAGS: dev
        volumes:
            - ./:/var/www/app_laravel
        networks:
            - app-network
#Docker Networks
networks:
    app-network:
        driver: bridge